In [1]:
import pickle

In [2]:
independent=pickle.load(open("LoadIndependentdata.sav","rb"))
dependent=pickle.load(open("Loaddependentdata.sav","rb"))

In [3]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [4]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [21]:
# Standard Scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [22]:
independent

array([[-1.43876426, -0.45332   , -0.90861367, -1.0105187 ,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719,  0.98959079, -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576,  0.98959079, -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, -1.0105187 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, -1.0105187 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, -1.0105187 ,  1.97058663]],
      shape=(1338, 5))

In [29]:
preinput=sc.transform([[25,28,2,1,0]])

In [30]:
preinput

array([[ 2.50000000e+01,  2.80000000e+01,  2.00000000e+00,
         1.00000000e+00, -1.06209676e-17]])

In [35]:
load_model=pickle.load(open("PreprocessedInputFile.sav","rb"))

In [36]:
Prediction=load_model.predict(preinput)

In [37]:
Prediction

array([17144.08729473])